### ISSUE TITLE
Shift / Enter key not working

### ISSUE THREAD

**Issue by neh** [keyboardio/Kaleidoscope-DualUse#11]
I've tried both `SFT_T(Enter)` and `MT(LeftShift, Enter)` and can't seem to get this to work. Should it? I have a Control/ESC key working properly, but the Shift/Enter key only functions as a Shift when held, and does nothing on tap.

**Comment by algernon** [comment]
It should work, and if it does not, that is a bug. Thank you for reporting it! Will try to get to the bottom of it soon.

**Comment by gedankenexperimenter** [comment]
Should that be `SFT_T(Key_Enter)`?

**Comment by algernon** [comment]
No, it shouldn't. `SFT_T` (via `MT`) prepends `Key_` already.

**Comment by dsummersl** [comment]
I've also tried something similar, without luck: `CTL_T(Enter)`. When set up tapping the key does nothing, and when held with another key (say ctl and w) it just prints the character.

**Comment by algernon** [comment]
Like with many other issues: can you try the [Qukeys](https://github.com/gedankenlab/Kaleidoscope-Qukeys) plugin? It supports the same in-keymap markup as `DualUse`, but works much more reliably.

**Comment by dsummersl** [comment]
I tried using the control/enter overlay with qukeys this morning: works great!

**Comment by algernon** [comment]
As the `DualUse` plugin is no more, and this setup works with `Qukeys`, I'm closing this issue.
