### ISSUE TITLE
Point people towards Qukeys

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope-DualUse#13]
[Qukeys](https://github.com/gedankenlab/Kaleidoscope-Qukeys) does everything `DualUse` does, but does it better. It even supports the same API, and as such, is a drop-in replacement.

We should point people to Qukeys, and perhaps even drop the current code, and just pull in Qukeys. Mind you, for this to be a practical thing to do, we'd need Qukeys in Arduino-Boards.

**Comment by gedankenexperimenter** [comment]
There are still two problems with Qukeys that make me hesitate. First, it's getting very large. One might even say "bloated". Not a big deal, as long as everything the user wants still fits in progmem.

The other problem is that it bypasses the HID façade and directly accesses objects in KeyboardioHID, so it won't work with other HID libraries unless they have the similar `Keyboard` objects.

I'm working on a rewrite of Kaleidoscope that would solve both problems (and should _drastically_ reduce the size of Qukeys, even with all the features that I want to add), but that's definitely a long-term project, not a short-term one.

**Comment by algernon** [comment]
For the time being, I think that having the features Qukeys provides far outweigh the cons, be that size (DualUse ain't exactly small, either), or not using the facade (not terribly urgent right now; the next keyboard to use Kaleidoscope will likely use `KeyboardioHID` too).

**Comment by gedankenexperimenter** [comment]
Well, I've certainly been pointing Model01 users to Qukeys as it is, so I don't really have any problem with doing so in the DualUse documentation, nor do I have a problem with it being included in Arduino-Boards, but I did want to bring that naughtiness (bypassing the HID façade) to your attention before any sort of official endorsement is made.

**Comment by gedankenexperimenter** [comment]
Also, I'll need to write some better user documentation…
