### ISSUE TITLE
Tap/Hold global for all keys

### ISSUE THREAD

**Issue by iGEL** [keyboardio/Kaleidoscope-DualUse#14]
I tried to press the combination `meta`+`shift`+`enter` (opens a terminal in Xmonad), but both the meta key as well as the enter key were defined as dual use with `GUI_T(Escape)` and `ALT_T(Enter)`. So, to perform this combination, I had to hold the `meta/esc` key and tap the `alt/enter` key  at the same time.

After debugging the scancodes, I realized that the keyboard seems to have only one global state to register, whether the dual keys would are being hold or tabs right now. At least it always send `alt`, even though I just tapped the `alt/enter` key.

I'm not sure whether it's worth fixing, but if not, I would at least document this limitation.

**Comment by gedankenexperimenter** [comment]
You might want to try [Qukeys](https://github.com/gedankenlab/Kaleidoscope-Qukeys) instead; it doesn't have this same limitation.

**Comment by algernon** [comment]
I'll second that, Qukeys is superior. Can you try that plugin instead?

(In the long term, I want to make DualUse just be a kind of alias to Qukeys...)

**Comment by algernon** [comment]
As `DualUse` is now an alias to `Qukeys`, I think this can be considered solved.
