### ISSUE TITLE
Issue with Fn key and arrow keys

### ISSUE THREAD

**Issue by sinkr** [keyboardio/Kaleidoscope-DualUse#15]
Hello,

I've remapped my Fn keys to match more or less what I was used to on my Kinesis Advantage Pro.

My left Fn key is DualUse'd to being backspace, and my right Fn key is DualUse'd to enter.

These work fine for the most part, however if I attempt to use the Fn key with the arrows, I get a character input.   For instance, if I hit Fn-Up arrow, I first get a 't' (I'm in Dvorak).

The convenience of DualUse is nice, but if I'm editing something on the bash CLI and want to arrow in, first getting a 'd' makes CLI editing very difficult.

Any ideas what's wrong?

**Comment by algernon** [comment]
Most likely `DualUse` is bugged. It's... not the best plugin out there, I'm afraid. Can you give [Qukeys](https://github.com/gedankenlab/Kaleidoscope-Qukeys) a try instead? It supports the DualUse-style markup, but is a much better thought out and implemented plugin.

In the not too distant future, I want to deprecated DualUse, and point people toward Qukeys, as that is a much better plugin, that can be used to achieve the same things, and more, with a fraction of the issues that plague DualUse itself.

**Comment by sinkr** [comment]
Absolutely!  Thank you for the tip.  I didnt't see Qukeys.  

Regards,

-R.
