### ISSUE TITLE
Dual use key works in every way... except tapping

### ISSUE THREAD

**Issue by indirect** [keyboardio/Kaleidoscope-DualUse#5]
So I am trying to set up the thumbkey `ctrl` as a dual-use key with `CTL_T(Escape)`. The relevant bit of keymap looks like this:

```
  [DVORAK] = KEYMAP_STACKED
  (___,          Key_1,         Key_2,     Key_3,      Key_4, Key_5, Key_LEDEffectNext,
   Key_Backtick, Key_Quote,     Key_Comma, Key_Period, Key_P, Key_Y, Key_Tab,
   Key_PageUp,   Key_A,         Key_O,     Key_E,      Key_U, Key_I,
   Key_PageDown, Key_Semicolon, Key_Q,     Key_J,      Key_K, Key_X, ShiftToLayer(SYMBOL),
   CTL_T(Escape), Key_Backspace, Key_LeftGui, Key_LeftShift,
   ShiftToLayer(FUNCTION),
```

As far as I can tell, everything is working... except that tapping the button doesn't emit an `escape`. Holding down for 1 second does trigger holding down `ctrl` by itself, and does fire an `escape` on release. Using it as a modifier key works perfectly. But tapping it doesn't do anything at all.

Am I missing something? Is this a known issue of some kind? Thanks!

**Comment by indirect** [comment]
Small update: I tried this out again tonight, but this time trying to see if I could convert the A key to a dual-use shift key. It wound up working the same way... great as a shift, no A when tapped, does emit an A when held down for a while and then released.

**Comment by algernon** [comment]
I think I see where the problem is. Sadly my Model01 prototype is acting up again, so testing things is a bit harder (not impossible, I'll just have to dig out my Shortcut prototype :p).

**Comment by algernon** [comment]
Reproduced the problem, with a few others: some of the logic is completely backwards: holding a DualUse key past the time-out should input the modifier, and not input the normal key, yet, it inputs both, by the looks of it.

**Comment by indirect** [comment]
Thank you!
