### ISSUE TITLE
Repeat with dual use keys

### ISSUE THREAD

**Issue by kejadlen** [keyboardio/Kaleidoscope-DualUse#8]
It currently does not seem possible to get key repeat on keys assigned to tap. On qmk, double-tapping and holding a tap-hold key will repeat that key.

**Comment by algernon** [comment]
Doing this is a bit more involved than I first anticipated, as it isn't something I thought of when creating the plugin. It's a feature worth implementing, but not a bug per se. Marking it as such, and will have another go at it this weekend, hopefully.

**Comment by gedankenexperimenter** [comment]
I'm strongly in favor of this feature. I really want DualUse letter keys to work, and Apple's system for inputting accented characters requires pressing and holding those keys (and makes it nearly impossible to set up a proper Compose key).

**Comment by algernon** [comment]
Because `DualUse` is now a wrapper around `Qukeys`, and that plugin has an issue about this very feature, I'm closing it. It's to be done on the `Qukeys` side of things.
